export const tags = [
  "Array",
  "String",
  "Hash Set",
  "Hash Table",
  "Two Pointers",
  "Sliding Window",
  "Linked List",
  "Stack",
  "Queue",
  "Tree",
  "Binary Search",
  "Graph",
  "DFS",
  "BFS",
  "Dijkstra",
  "Topological Sort",
  "Prefix",
  "Suffix",
  "Heap",
  "Backtracking",
  "Dynamic Programming",
  "Greedy",
  "Sorting",
  "Bit Manipulation",
  "Math",
  "Matrix",
  "Recursion",
  "Trie",
  "Brute Force",
  "Memoization",
  "Binary Search Tree",
  "Binary Tree",
]
